# .goreleaser.yaml
project_name: sync
release:
  github:
    owner: matthewdavidson09
    name: dynamic-distro-groups
  draft: false
  prerelease: false

builds:
  - id: sync
    main: ./cmd/app/main.go
    binary: dynamic-sync
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - .env.example

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
